apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: todo
      tier: backend
      track: stable
  template:
    metadata:
      labels:
        app: todo
        tier: backend
        track: stable
    spec:
      containers:
        - name: todo
          image: "gcr.io/<GCP_PROJECT_ID>/<CI_REGISTRY_GKE_IMAGE>:<VERSION>"
          ports:
            - name: http
              containerPort: 80
          env:
          - name: APP_ENV
            value: deploy
